# Generated by Django 3.2 on 2021-07-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_pic'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='Comment',
        ),
    ]
